import { chromium } from 'playwright';
const dir = process.argv[2] ?? '.';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 960, height: 600 } });
const errors = [];
page.on('console', (m) => { if (['error', 'warning'].includes(m.type())) errors.push(`${m.type()}: ${m.text()}`); });
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
await page.goto('http://localhost:5173/?scene=Game');
await page.waitForTimeout(1200);
const put = (x, y, a) => page.evaluate(([x, y, a]) => { const p = window.__bc.world.player; p.x = x; p.y = y; p.angle = a; }, [x, y, a]);
const shot = async (n) => { await page.waitForTimeout(500); await page.screenshot({ path: `${dir}/${n}.png` }); };

await put(14.5, 1.5, 0); await shot('p1_key_view');
await put(16.6, 1.5, 0); await page.keyboard.down('w'); await page.waitForTimeout(500); await page.keyboard.up('w');
await shot('p2_key_taken');
await put(14.5, 10.5, 0); await shot('p3_shotgun_view');
await page.evaluate(() => { for (const z of window.__bc.world.zombies) { z.x = 1.5; z.y = 1.5; } });
await put(3.5, 17.8, Math.PI / 2);
await page.keyboard.down('f'); await page.waitForTimeout(100); await page.keyboard.up('f');
await page.waitForTimeout(2000);
await shot('p4_arena_open');
await put(3.5, 20.6, Math.PI / 2); await page.keyboard.down('w'); await page.waitForTimeout(500); await page.keyboard.up('w');
await put(3.5, 22.0, Math.atan2(8.5, 6)); await shot('p5_boss_approaching');
await page.keyboard.press('3');
await page.keyboard.down('Space'); await page.waitForTimeout(1500); await page.keyboard.up('Space');
await shot('p6_smg_firing');
await page.evaluate(() => { window.__bc.world.boss.hurt(1e9, 0, 1, 0); });
await put(9.5, 32.8, Math.PI / 2); await page.waitForTimeout(300);
await page.keyboard.down('f'); await page.waitForTimeout(100); await page.keyboard.up('f');
await page.waitForTimeout(2000);
await shot('p7_exit_open');
await page.keyboard.down('w'); await page.waitForTimeout(1500); await page.keyboard.up('w');
await shot('p8_win');
const st = await page.evaluate(() => ({ key: window.__bc.world.hasKey, won: window.__bc.world.won, boss: !!window.__bc.world.boss, smg: window.__bc.world.weapon.def.id, fps: Math.round(window.__bc.game.loop.actualFps) }));
console.log(JSON.stringify(st), errors.length ? errors : 'clean console');
await browser.close();
